# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            "AI4WORK"
tagline:          ''
description:      'International workshop on AI for Human Resources and Public Employment Services'
url:              https://ai4work.github.io/ecmlpkdd2025/
baseurl:          https://ai4work.github.io/ecmlpkdd2025/
destination:      _site

author:
  name:           'Bo Kang'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ai4work/ecmlpkdd2025

plugins:
  - jekyll-paginate
  - jekyll-gist

